// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'duplicate-custom-field-description'
  | 'duplicate-custom-field-title'
  | 'invalid-custom-field-description'
  | 'invalid-custom-field-title'
  | 'pref-custom-fields-button-add'
  | 'pref-custom-fields-button-reset'
  | 'pref-custom-fields-button-save'
  | 'pref-custom-fields-header-delete'
  | 'pref-custom-fields-header-name'
  | 'pref-custom-fields-header-number'
  | 'pref-custom-fields-header-position'
  | 'pref-custom-fields-title'
  | 'pref-help'
  | 'prefs-custom-field-position-after-creators'
  | 'prefs-custom-field-position-end'
  | 'prefs-custom-field-position-start'
  | 'prefs-title';
